spring.application.name=TransactionMicroservice

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:free
spring.datasource.username=system
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Eureka is not being used yet.
eureka.client.enabled=false