package com.oracle.transactionmicroservice.dto.request;

import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.math.BigDecimal;

// There is also no AddAccountRequest
// because the account owner comes from the JWT and the opening balance is randomly generated by the service.

public record AddFundsRequest(

        @NotNull(message = "Account ID is required.")
        @Positive(message = "Account ID must be greater than zero.")
        Long accountId,

        @NotNull(message = "Amount is required.")
        @Positive(message = "Amount must be greater than zero.")
        @Digits(
                integer = 18,
                fraction = 2,
                message = "Amount must contain up to 18 whole digits and 2 decimal places."
        )
        BigDecimal amount
) {
}