spring.application.name=CONTACT-SERVICE
server.port=8082

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/FREE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.healthcheck.enabled=true
eureka.instance.prefer-ip-address=false
eureka.instance.ip-address=127.0.0.1

contact-service.user-service.internal-token=${USER_SERVICE_INTERNAL_TOKEN}
contact-service.user-service.connect-timeout=2s
contact-service.user-service.read-timeout=3s

contact-service.jwt.public-key=${JWT_PUBLIC_KEY:}
contact-service.internal.service-token=${INTERNAL_SERVICE_TOKEN:}
